site_name: Api Pedidos Digitais
nav:
  - Início: index.md
  - Grupos de usuários:
      - "Listar": "groups/index.md"
      - "Visualizar": "groups/show.md"
      - "Permissões": "groups/permissions.md"
  - Usuários:
      - "Listar": "users/index.md"
      - "Visualizar": "users/show.md"
      - "Cadastrar": "users/create.md"
      - "Alterar": "users/update.md"
      - "Remover": "users/delete.md"
  - Clientes:
      - "Listar": "companies/index.md"
      - "Visualizar": "companies/show.md"
      - "Cadastrar": "companies/create.md"
      - "Alterar": "companies/update.md"
      - "Remover": "companies/delete.md"
  - Lojas:
      - "Listar": "stores/index.md"
      - "Visualizar": "stores/show.md"
      - "Cadastrar": "stores/create.md"
      - "Alterar": "stores/update.md"
      - "Remover": "stores/delete.md"
  - Categorias:
      - "Listar": "categories/index.md"
      - "Visualizar": "categories/show.md"
      - "Cadastrar": "categories/create.md"
      - "Alterar": "categories/update.md"
      - "Remover": "categories/delete.md"
  - Produtos:
      - "Listar": "products/index.md"
      - "Visualizar": "products/show.md"
      - "Cadastrar": "products/create.md"
      - "Alterar": "products/update.md"
      - "Remover": "products/delete.md"
  - Imagem Produtos:
      - "Listar": "products/images/index.md"
      - "Visualizar": "products/images/show.md"
      - "Cadastrar": "products/images/create.md"
      - "Alterar": "products/images/update.md"
      - "Remover": "products/images/delete.md"
  - Campos Personalizados:
      - "Listar": "custom_fields/index.md"
      - "Visualizar": "custom_fields/show.md"
      - "Cadastrar": "custom_fields/create.md"
      - "Alterar": "custom_fields/update.md"
      - "Remover": "custom_fields/delete.md"
  - Valores dos Campos Personalizados:
      - "Listar": "custom_values/index.md"
      - "Cadastrar": "custom_values/create.md"
      - "Alterar": "custom_values/update.md"
      - "Remover": "custom_values/delete.md"
  - Variações precificadas:
      - "Listar": "products/variations/index.md"
      - "Visualizar": "products/variations/show.md"
      - "Cadastrar": "products/variations/create.md"
      - "Alterar": "products/variations/update.md"
      - "Remover": "products/variations/delete.md"
  - Status dos pedidos:
      - "Listar": "orders/status/index.md"
      - "Visualizar": "orders/status/show.md"
      - "Cadastrar": "orders/status/create.md"
      - "Alterar": "orders/status/update.md"
      - "Remover": "orders/status/delete.md"
  - Pedidos:
      - "Listar": "orders/index.md"
      - "Visualizar": "orders/show.md"
      - "Alterar": "orders/update.md"
  - Uploads:
      - "Enviar": "uploads/create.md"
theme: readthedocs
